services:
  app-blue:
    image: sergitohh/sportsclub_cdci:latest
    restart: always

  app-green:
    image: sergitohh/sportsclub_cdci:latest
    restart: always

  postgres:
    restart: always
    ports: !override [] # Força el tancamet dels ports heredats.

  nginx:
    restart: always
    ports:
      - "80:80" # Només NGINX es visible a l'exterior
